version: '3.7'

services:
  mysql:
    container_name: musicas-mysql
    image: musicas-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - musicas-network
    ports:
      - 3307:3306
  app:
    depends_on:
      - mysql
    container_name: musicas-app
    image: musicas-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - musicas-network

networks:
  musicas-network:
